# Source: https://pre-commit.com
# Supported hooks: https://pre-commit.com/hooks.html
---
exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: client-java/sounds/
      - id: check-symlinks
      - id: name-tests-test
      - id: requirements-txt-fixer
  # Prohibit tabs in files
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-tabs
        files: .(hs|lhs|cs|pxd|py|py3|pyw|pyx|pyz|pyi|c|cc|cxx|cpp|c\+\+|hpp|h|h\+\+|hh|R|java)
  # Lint yaml files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: ["--config-data={
          extends: default,
          rules:{new-lines: disable, line-length: {max: 140}}
          }"]
  # Lint bash files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
  # Java formatter
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.6.0
    hooks:
      - id: pretty-format-java
        args: [--autofix]
  # PMD
  # - repo: https://github.com/gherynos/pre-commit-java
    # rev: v0.2.0  # Use the ref you want to point at
    # hooks:
      # - id: pmd
        # exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
