# Source: https://pre-commit.com
# Supported hooks: https://pre-commit.com/hooks.html
---
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-symlinks
      - id: name-tests-test
      - id: requirements-txt-fixer
  # Prohibit tabs in files
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-tabs
        files: .(hs|lhs|cs|pxd|py|py3|pyw|pyx|pyz|pyi|c|cc|cxx|cpp|c\+\+|hpp|h|h\+\+|hh|R|java)
  # - repo: https://github.com/psf/black
  #   rev: 19.3b0
  #   hooks:
  #     - id: black
  # Lint yaml files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: ["--config-data={
          extends: default,
          rules:{new-lines: disable, line-length: {max: 140}}
          }"]
  # Lint bash files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
  # Lint gitlab ci files
  # - repo: https://gitlab.com/devopshq/gitlab-ci-linter
  #   rev: v1.0.3
  #   hooks:
  #     - id: gitlab-ci-linter
  # Lint dockerfiles
  - repo: https://github.com/hadolint/hadolint
    rev: v2.7.0
    hooks:
      - id: hadolint
  # Lint terraform files
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.50.0
  #   hooks:
  #     - id: terraform_tflint
  #     - id: terraform_validate
  #     - id: terraform_docs
  #     - id: terraform_docs_replace
  - repo: local
    hooks:
      - id: hlint
        name: HLint
        entry: hlint # Uses local hlint
        language: python
        files: .l?hs
      - id: ormolu
        name: Ormolu formatter
        entry: ormolu
        language: python
        files: .l?hs
        args: [--mode, inplace]
