# Source: https://pre-commit.com
# Supported hooks: https://pre-commit.com/hooks.html
---
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
      - id: check-xml
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
      - id: end-of-file-fixer
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
      - id: trailing-whitespace
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
      - id: check-added-large-files
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
      - id: check-symlinks
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
      - id: name-tests-test
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
      - id: requirements-txt-fixer
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
  # Prohibit tabs in files
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-tabs
        files: .(hs|lhs|cs|pxd|py|py3|pyw|pyx|pyz|pyi|c|cc|cxx|cpp|c\+\+|hpp|h|h\+\+|hh|R|java)
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
  # Lint yaml files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: ["--config-data={
          extends: default,
          rules:{new-lines: disable, line-length: {max: 140}}
          }"]
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
  # Lint bash files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
        exclude: server-python/lib/|server-python/nethack-server-env/|client-java/target/
